### ISSUE TITLE
DAO: Voting

### ISSUE THREAD

**Issue by thisisommore** [NetSepio/gateway#133]
- [POST] /report
   - title: string
   - description: string
   - image: ipfs
   - document: ipfs
   - category: string
   - tags: string[]
   - projectName: string
   - projectDomain: string (netsepio.com)
 
- [POST] /report/vote
   - reportId
   - upvote, downvote, notsure
- [GET] /report (pagination)
   - filters title, projectDomain, projectName, category, tags
  
-----
DB

table name - `reports`
id uuid
description: string
image: ipfs[]
document: ipfs
category: string
tags: string[]
projectName: string
projectDomain: string (netsepio.com)
status: "accepted"|"rejected"|"running"
created: uuid (of user)

**Comment by Shachindra** [comment]
Can you make the image field as array?
