### ISSUE TITLE
paseto: use public key

### ISSUE THREAD

**Issue by thisisommore** [NetSepio/gateway#59]
1. Generate the private key on the app start - Need not take the privKey from .env
2. Create a /status API where the details of app is shared along with the publicKey
Response: version, network, pasetoPublicKey, goVersion

**Comment by thisisommore** [comment]
so after each new deployment private key will change?

**Comment by thisisommore** [comment]
@Shachindra

**Comment by Shachindra** [comment]
Yes. Thats why there's the status API so people can verify using the public key provided

**Comment by thisisommore** [comment]
Okay, but if the private key changes, the token might failed to verify? So after each deployment all issues token becomes invalid?

**Comment by Shachindra** [comment]
Lets use the .env for the privKey fo now
