### ISSUE TITLE
NFT Mint APIs

### ISSUE THREAD

**Issue by Shachindra** [NetSepio/gateway#97]
We need to provide NFTs for free mint to our early users. This will also enable them to access other features for trial such as VPN, Firewall and Bots.

Req.

1. NFT Collection that have both Mint and Delegate Mint function to issue NFTs
2. The delegateMint function needs the operator role
3. APIs to call the delegateMint function of the specific contract

**Comment by thisisommore** [comment]
So our backend will have delegate mint api, and it will check if wallet is in waitlist or not, if it is there then we will issue nft?

**Comment by huisq** [comment]
Yes smart contract will check if free NFT minter is <= 500
